services:
    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - importer-api
        networks:
            - importer-network

    importer-api:
        ports:
            - "9000:9000"
        build:
            context: .
        volumes:
            - ./:/var/www
            - vendor:/var/www/vendor
        depends_on:
            - db
        networks:
            - importer-network

    db:
        image: mysql:8.4
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: importer
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - importer-network

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - importer-network
        volumes:
            - redisdata:/data


networks:
    importer-network:

volumes:
    dbdata:
        driver: local
    vendor:
        driver: local
    redisdata:
        driver: local
